// import Land from 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fxn--r1a.website%2Fs%2Fhuquqiy_axborot%3Fbefore%3D4822&psig=AOvVaw3jZ2IDAc6f8AF-Np62fo7q&ust=1646651668009000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCIjLy-DwsfYCFQAAAAAdAAAAABAD'

export const favorit = [
  {
    id: 1,
    // img: Land,
    titles: "New Apartment Nice Wiedfefw",
    location: "Quincy St, Brooklyn, NY, USA",
    oldcost: "$2,800/mo",
    cost: "$7,500/mo",
  },
  {
    id: 2,
    // img: Land,
    titles: "New Apartment Nice Wiew",
    location: "Quincy St, Brooklyn, NY, USA",
    oldcost: "$2,800/mo",
    cost: "$7,500/mo",
  },
  {
    id: 3,
    // img: Land,
    titles: "New Apartment Nice Wiew",
    location: "Quincy St, Brooklyn, NY, USA",
    oldcost: "$2,800/mo",
    cost: "$7,500/mo",
  },
  {
    id: 4,
    // img: Land,
    titles: "New Apartment Nice Wiew",
    location: "Quincy St, Brooklyn, NY, USA",
    oldcost: "$2,800/mo",
    cost: "$7,500/mo",
  },
  {
    id: 5,
    // img: Land,
    titles: "New Apartment Nice Wiew",
    location: "Quincy St, Brooklyn, NY, USA",
    oldcost: "$2,800/mo",
    cost: "$7,500/mo",
  },
  {
    id: 6,
    // img: Land,
    titles: "New Apartment Nice Wiew",
    location: "Quincy St, Brooklyn, NY, USA",
    oldcost: "$2,800/mo",
    cost: "$7,500/mo",
  },
  {
    id: 7,
    // img: Land,
    titles: "New Apartment Nice Wiew",
    location: "Quincy St, Brooklyn, NY, USA",
    oldcost: "$2,800/mo",
    cost: "$7,500/mo",
  },
  {
    id: 8,
    // img: Land,
    titles: "New Apartment Nice Wiew",
    location: "Quincy St, Brooklyn, NY, USA",
    oldcost: "$2,800/mo",
    cost: "$7,500/mo",
  },
  {
    id: 9,
    // img: Land,
    titles: "New Apartment Nice Wiew",
    location: "Quincy St, Brooklyn, NY, USA",
    oldcost: "$2,800/mo",
    cost: "$7,500/mo",
  },
  {
    id: 10,
    // img: Land,
    titles: "New Apartment Nice Wiew",
    location: "Quincy St, Brooklyn, NY, USA",
    oldcost: "$2,800/mo",
    cost: "$7,500/mo",
  },
  {
    id: 11,
    // img: Land,
    titles: "New Apartment Nice Wiew",
    location: "Quincy St, Brooklyn, NY, USA",
    oldcost: "$2,800/mo",
    cost: "$7,500/mo",
  },
  {
    id: 12,
    // img: Land,
    titles: "New Apartment Nice Wiew",
    location: "Quincy St, Brooklyn, NY, USA",
    oldcost: "$2,800/mo",
    cost: "$7,500/mo",
  },
];